<?php

namespace App\Models;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;


class Page extends BaseModel
{
    protected $fillable = [
        'title',
        'title_alias',
        'summary',
        'content',
        'image',
        'public',
        'featured',
        'params',
        'hits',
        'created_by'
    ];

    /**
     *
     */
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        if (Request::segment(1) == 'admin') {
            static::creating(function ($page) {
                $page->created_by = Auth::user()->id;
                $page->updated_by = Auth::user()->id;
            });

            static::updating(function ($page) {
                $page->updated_by = Auth::user()->id;
            });

            static::deleting(function ($page) {

            });
        }
    }
}
