<?php

namespace App\Models;

class Province extends BaseModel
{
    public $timestamps = false;
    protected $fillable = ['code', 'name', 'slug_name'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public static function getList($prependList = [], $appendList = [])
    {
        $all  = self::all(['id', 'name'])->toArray();
        $list = array_column($all, 'name', 'id');
        foreach ($list as $key => $title)
            $prependList[$key] = $title;
        foreach ($appendList as $key => $title)
            $prependList[$key] = $title;
        return $prependList;
    }

    public function districts()
    {
        return $this->hasMany(District::class);
    }
}
